version: "3.8"
services:
  server:
    image: demo
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testapp?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=testapp
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net:
